channels:
  - ncar
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aiohttp=3.8.1=py39h3811e60_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alabaster=0.7.12=py_0
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.5.0=py39hf3d152e_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39h3811e60_1
  - asciitree=0.3.3=py_2
  - astropy=5.0.1=py39hce5d2b2_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=20.3.0=pyhd3deb0d_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_4
  - black=21.12b0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - bokeh=2.4.2=py39hf3d152e_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py39h3811e60_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cachy=0.3.0=py_0
  - cartopy=0.20.2=py39hc85cdae_3
  - certifi=2021.10.8=py39hf3d152e_2
  - cf_xarray=0.7.0=pyhd8ed1ab_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cftime=1.5.2=py39hce5d2b2_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - cleo=0.8.1=pyhd8ed1ab_2
  - click=8.0.3=py39hf3d152e_1
  - click-completion=0.5.2=py39hf3d152e_3
  - click-default-group=1.2.2=pyhd8ed1ab_1
  - click-log=0.3.2=pyh9f0ad1d_0
  - clikit=0.6.2=pyh9f0ad1d_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - cmcrameri=1.4=pyhd8ed1ab_0
  - cmip6_preprocessing=0.5.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda-lock=1.0.5=pyhd8ed1ab_0
  - crashtest=0.3.1=pyhd8ed1ab_0
  - cryptography=36.0.1=py39h95dcef6_0
  - curl=7.81.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39h3811e60_1
  - dask=2022.1.0=pyhd8ed1ab_0
  - dask-core=2022.1.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.3.4=pyhd8ed1ab_0
  - distributed=2022.1.0=py39hf3d152e_0
  - docutils=0.16=py39hf3d152e_3
  - ensureconda=1.4.2=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - eofs=1.4.0=py_0
  - esmf=8.2.0=nompi_h61edca3_0
  - esmpy=8.2.0=nompi_py39hc8aa433_1
  - executing=0.8.2=pyhd8ed1ab_0
  - expat=2.4.3=h9c3ff4c_0
  - fasteners=0.16=pyhd8ed1ab_0
  - filelock=3.6.0=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.28.5=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.2.0=py39h3811e60_1
  - fsspec=2022.1.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=11.2.0=h82a94d6_11
  - gcc_linux-64=11.2.0=h39a9532_4
  - gcsfs=2022.1.0=pyhd8ed1ab_0
  - geocat-comp=2021.10.0=py_0
  - geocat-f2py=2021.08.0=py39h3d0eb6f_0
  - geos=3.10.2=h9c3ff4c_0
  - gettext=0.19.8.1=h73d1719_1008
  - gfortran_impl_linux-64=11.2.0=h7a446d4_11
  - gfortran_linux-64=11.2.0=h777b47f_4
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - google-api-core=2.4.0=pyhd8ed1ab_0
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-cloud-core=2.2.2=pyh6c4a22f_0
  - google-cloud-storage=2.0.0=pyh6c4a22f_0
  - google-crc32c=1.1.2=py39hb81f231_2
  - google-resumable-media=2.1.0=pyh6c4a22f_0
  - googleapis-common-protos=1.54.0=py39hf3d152e_0
  - grpcio=1.42.0=py39hff7568b_0
  - gst-plugins-base=1.18.5=hf529b03_3
  - gstreamer=1.18.5=h9f60fe5_3
  - h5py=3.6.0=nompi_py39h7e08c79_100
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_103
  - heapdict=1.0.1=py_0
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py39hf3d152e_0
  - importlib_metadata=4.10.1=hd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intake=0.6.5=pyhd8ed1ab_0
  - intake-stac=0.3.0=py_0
  - intake-xarray=0.6.0=pyhd8ed1ab_0
  - ipykernel=6.7.0=py39hef51801_0
  - ipython=8.0.1=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py39hf3d152e_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter-book=0.10.2=pyhd8ed1ab_0
  - jupyter-cache=0.4.3=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.5=pyhc268e32_0
  - jupyter-sphinx=0.3.2=pyhd8ed1ab_1
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - jupyter_server=1.13.5=pyhd8ed1ab_1
  - jupyterbook-latex=0.2.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - jupytext=1.10.3=pyh44b312d_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libclang=13.0.0=default_hc23dcda_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=7.81.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=11.2.0=h0952999_11
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.2=h174f98d_1
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libllvm13=13.0.0=hf817b99_0
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.43.0=h812cca2_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.1=hd57d9b9_1
  - libprotobuf=3.19.3=h780b84a_0
  - libsanitizer=11.2.0=he4da1e4_11
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzip=1.8.0=h4de3113_1
  - libzlib=1.2.11=h36c2ea0_1013
  - linkify-it-py=1.0.3=pyhd8ed1ab_0
  - llvmlite=0.38.0=py39h1bbdace_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown-it-py=0.6.2=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib=3.5.1=py39hf3d152e_0
  - matplotlib-base=3.5.1=py39h2fa2bec_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdit-py-plugins=0.2.6=pyhd8ed1ab_0
  - metpy=1.2.0=pyhd8ed1ab_0
  - mistune=0.8.4=py39h3811e60_1005
  - monotonic=1.5=py_0
  - msgpack-python=1.0.3=py39h1a9c180_0
  - multidict=6.0.1=py39h3811e60_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py39hf3d152e_4
  - mysql-common=8.0.28=ha770c72_0
  - mysql-libs=8.0.28=hfa10184_0
  - myst-nb=0.12.3=pyhd8ed1ab_0
  - myst-parser=0.13.7=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=5.6.1=pyhd8ed1ab_2
  - nbdime=3.1.1=pyhd8ed1ab_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h9c3ff4c_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nested-lookup=0.2.23=pyhd8ed1ab_0
  - netcdf-fortran=4.5.4=nompi_h2b6e579_100
  - netcdf4=1.5.8=nompi_py39h64b754b_101
  - notebook=6.4.8=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.74=hb5efdd6_0
  - numba=0.55.0=py39h56b8d98_0
  - numcodecs=0.9.1=py39he80948d_2
  - numpy=1.21.5=py39haac66dc_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1n=h166bdaf_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.4.0=py39hde0f152_0
  - pandoc=2.17.0.1=ha770c72_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pastel=0.2.1=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39ha612740_0
  - pint=0.18=pyhd8ed1ab_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pkginfo=1.8.2=pyhd8ed1ab_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - poetry=1.1.13=py39hf3d152e_1
  - poetry-core=1.0.8=py39hf3d152e_1
  - pooch=1.6.0=pyhd8ed1ab_0
  - proj=8.2.1=h277dcde_0
  - prometheus_client=0.13.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - protobuf=3.19.3=py39he80948d_0
  - psutil=5.9.0=py39h3811e60_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.1=py39hf3d152e_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.9.0=py39hb9d737c_1
  - pydata-sphinx-theme=0.7.2=pyhd8ed1ab_0
  - pyerfa=2.0.0.1=py39hce5d2b2_1
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pylev=1.4.0=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py39hab5ddba_1
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pyrsistent=0.18.1=py39h3811e60_0
  - pyshp=2.1.3=pyh44b312d_0
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.9=h62f1059_0_cpython
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=22.3.0=py39h37b5a0c_1
  - qt=5.12.9=ha98a1a1_5
  - readline=8.1=h46c0cb4_0
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - requests-toolbelt=0.9.1=py_0
  - rsa=4.8=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py39hb9d737c_1
  - ruamel.yaml.clib=0.2.6=py39hb9d737c_1
  - sat-stac=0.4.1=pyh44b312d_0
  - scipy=1.7.3=py39hee8e79c_0
  - secretstorage=3.3.2=py39hf3d152e_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=59.8.0=py39hf3d152e_0
  - shapely=1.8.0=py39ha65c37e_5
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sniffio=1.2.0=py39hf3d152e_2
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sparse=0.13.0=pyhd8ed1ab_0
  - sphinx=3.5.4=pyh44b312d_0
  - sphinx-book-theme=0.2.0=pyhd8ed1ab_1
  - sphinx-comments=0.0.3=pyh9f0ad1d_0
  - sphinx-copybutton=0.5.0=pyhd8ed1ab_0
  - sphinx-panels=0.5.2=pyhd3deb0d_0
  - sphinx-thebe=0.1.1=pyhd8ed1ab_0
  - sphinx-togglebutton=0.2.3=pyhd3deb0d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=2.1.4=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_1
  - sqlalchemy=1.3.23=py39h3811e60_0
  - sqlite=3.37.0=h9cd32fc_0
  - stack_data=0.1.4=pyhd8ed1ab_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.13.1=py39hf3d152e_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=1.2.2=pyhd8ed1ab_0
  - tomlkit=0.10.2=pyha770c72_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py39h3811e60_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.0.1=hd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - virtualenv=20.14.1=py39hf3d152e_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py39hf3d152e_1
  - xarray=0.21.1=pyhd8ed1ab_0
  - xarrayutils=1.0.0=pyhd8ed1ab_0
  - xesmf=0.6.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39h3811e60_1
  - zarr=2.11.0=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.0.0=py_0
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - arrow==1.2.2
    - binaryornot==0.4.4
    - cachecontrol==0.12.11
    - chardet==4.0.0
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cookiecutter==1.7.3
    - fastprogress==1.0.0
    - fiona==1.8.20
    - geopandas==0.10.2
    - h5netcdf==0.13.1
    - intake-esm==2021.8.17
    - intake-geopandas==0.4.0
    - jinja2-time==0.2.0
    - keyring==23.5.0
    - lockfile==0.12.2
    - munch==2.5.0
    - poyo==0.5.0
    - python-dateutil==2.8.2
    - python-slugify==6.1.1
    - text-unidecode==1.3
